version: '3.8'

services:
  # ========================================
  # BASE DE DATOS H2
  # ========================================


  h2-database:
    build: ./h2-database-service
    container_name: h2-database
    ports:
      - "9092:9092"  # Puerto TCP para conexiones JDBC
    environment:
      - H2_DATA_DIR=/data
      - H2_PORT=9092
    volumes:
      - h2-data:/data
    networks:
      - hospital-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "java", "-cp", "h2.jar", "org.h2.tools.Server", "-tcpShutdown", "tcp://localhost:9092"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ========================================
  # EUREKA SERVER
  # ========================================
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_REGISTERWITHEUREKA=false
      - EUREKA_CLIENT_FETCHREGISTRY=false
    networks:
      - hospital-network
    restart: unless-stopped
    depends_on:
      - h2-database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ========================================
  # MICROSERVICIOS
  # ========================================
  doctor-service:
    build: ./doctor-service
    container_name: doctor-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://h2-database:9092/hospitaldb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_PREFERIPADDRESS=true
    networks:
      - hospital-network
    restart: unless-stopped
    depends_on:
      - h2-database
      - eureka-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  citas-service:
    build: ./citas-service
    container_name: citas-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://h2-database:9092/hospitaldb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_PREFERIPADDRESS=true
    networks:
      - hospital-network
    restart: unless-stopped
    depends_on:
      - h2-database
      - eureka-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  especialidad-service:
    build: ./especialidad-service
    container_name: especialidad-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://h2-database:9092/hospitaldb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_PREFERIPADDRESS=true
    networks:
      - hospital-network
    restart: unless-stopped
    depends_on:
      - h2-database
      - eureka-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ========================================
  # API GATEWAY
  # ========================================
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_PREFERIPADDRESS=true
      - SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED=true
    networks:
      - hospital-network
    restart: unless-stopped
    depends_on:
      - eureka-server
      - doctor-service
      - citas-service
      - especialidad-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ========================================
  # MONITORING (OPCIONAL)
  # ========================================
  # Prometheus para métricas
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - hospital-network
    restart: unless-stopped

  # Grafana para visualización
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - hospital-network
    restart: unless-stopped

# ========================================
# VOLÚMENES
# ========================================G
volumes:
  h2-data:
    driver: local
  grafana-data:
    driver: local

# ========================================
# REDES
# ========================================
networks:
  hospital-network:
    driver: bridge 