services:
  - type: web
    name: h2-database
    runtime: docker
    dockerfilePath: ./h2-database-service/Dockerfile
    envVars:
      - key: H2_USER
        value: sa
      - key: H2_PASSWORD
        value: password
      - key: H2_PORT
        value: 9092
      - key: H2_WEB_PORT
        value: 8082
    plan: starter
    autoDeploy: true

  - type: web
    name: eureka-server
    runtime: docker
    dockerfilePath: ./eureka-server/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: docker
      - key: EUREKA_CLIENT_REGISTERWITHEUREKA
        value: false
      - key: EUREKA_CLIENT_FETCHREGISTRY
        value: false
    plan: starter
    autoDeploy: true

  - type: web
    name: doctor-service
    runtime: docker
    dockerfilePath: ./doctor-service/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: jdbc:h2:tcp://h2-database:9092/file:/opt/h2/hospitaldb
      - key: SPRING_DATASOURCE_USERNAME
        value: sa
      - key: SPRING_DATASOURCE_PASSWORD
        value: password
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://eureka-server:8761/eureka/
      - key: SPRING_DATA_ELASTICSEARCH_URIS
        value: https://j78qu5rxgf:c3y0l8bm9z@hospital-cluster-5303791460.us-east-1.bonsaisearch.net:443
      - key: ELASTICSEARCH_ENABLED
        value: true
      - key: ELASTICSEARCH_FALLBACK_ENABLED
        value: false
    plan: starter
    autoDeploy: true

  - type: web
    name: citas-service
    runtime: docker
    dockerfilePath: ./citas-service/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: jdbc:h2:tcp://h2-database:9092/file:/opt/h2/hospitaldb
      - key: SPRING_DATASOURCE_USERNAME
        value: sa
      - key: SPRING_DATASOURCE_PASSWORD
        value: password
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://eureka-server:8761/eureka/
    plan: starter
    autoDeploy: true

  - type: web
    name: especialidad-service
    runtime: docker
    dockerfilePath: ./especialidad-service/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: jdbc:h2:tcp://h2-database:9092/file:/opt/h2/hospitaldb
      - key: SPRING_DATASOURCE_USERNAME
        value: sa
      - key: SPRING_DATASOURCE_PASSWORD
        value: password
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://eureka-server:8761/eureka/
    plan: starter
    autoDeploy: true

  - type: web
    name: api-gateway
    runtime: docker
    dockerfilePath: ./api-gateway/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: docker
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://eureka-server:8761/eureka/
      - key: SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED
        value: true
    plan: starter
    autoDeploy: true

  - type: web
    name: prometheus
    runtime: docker
    image: prom/prometheus:latest
    plan: starter
    autoDeploy: true

  - type: web
    name: grafana
    runtime: docker
    image: grafana/grafana:latest
    envVars:
      - key: GF_SECURITY_ADMIN_PASSWORD
        value: admin
    plan: starter
    autoDeploy: true