services:
  - name: doctor-service
    rootDir: doctor-service
    type: worker
    dockerfilePath: Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: dev
      - key: SPRING_DATASOURCE_URL
        value: jdbc:h2:tcp://h2-database:9092/~/hospitaldb
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://eureka-server:8761/eureka/

  - name: h2-database
    runtime: docker
    type: worker
    rootDir: h2-database-service
    dockerfilePath: Dockerfile

  - name: eureka-server
    type: worker
    rootDir: eureka-server
    dockerfilePath: Dockerfile

  - name: api-gateway
    type: worker
    rootDir: api-gateway
    dockerfilePath: Dockerfile
    envVars:
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://eureka-server:8761/eureka/
