server:
  port: 8083

spring:
  application:
    name: citas-service
  cloud:
    compatibility-verifier:
      enabled: false # Opcional para evitar errores por versiones
  main:
    allow-bean-definition-overriding: true # Si usás Feign más adelante
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://shinkansen.proxy.rlwy.net:48598/railway}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:yIWMnmMBiULXeDZIogRKIGXzpYxIHghT}
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
  # h2:
  #   console:
  #     enabled: false
  #     path: /h2-console
  flyway:
    enabled: false

  jackson:
    default-property-inclusion: non-null
    serialization:
      write-dates-as-timestamps: false

# Configuración de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: ${EUREKA_INSTANCE_PREFERIPADDRESS:true}
    hostname: ${HOSTNAME:localhost}

# Configuración de Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Configuración de Swagger
springdoc:
  swagger-ui:
    path: /appointments/swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
  api-docs:
    path: /v3/api-docs

# Configuración de OpenFeign
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  circuitbreaker:
    enabled: true
