server:
  port: 8081 # O el puerto que prefieras

spring:
  application:
    name: doctor-service
  cloud:
    compatibility-verifier:
      enabled: false # Opcional para evitar errores por versiones
  main:
    allow-bean-definition-overriding: true # Si usás Feign más adelante
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.h2.Driver
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: false

  jackson:
    default-property-inclusion: non-null
    serialization:
      write-dates-as-timestamps: false
info:
  app:
    name: Doctor Service (Dev)
    version: 1.0.0
