spring:
  application:
    name: doctor-service
  cloud:
    compatibility-verifier:
      enabled: false # Opcional para evitar errores por versiones
  main:
    allow-bean-definition-overriding: true # Si usás Feign más adelante
  datasource:
    url: jdbc:h2:/opt/h2/hospitaldb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        transaction:
          jta:
            # Si no usás JTA, podés usar NoJtaPlatform
            #platform: org.hibernate.service.jta.platform.internal.NoJtaPlatform
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform

  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: false

  jackson:
    default-property-inclusion: non-null
    serialization:
      write-dates-as-timestamps: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
