server:
  port: 8081

spring:
  application:
    name: doctor-service
  cloud:
    compatibility-verifier:
      enabled: false
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
    hostname: doctor-service
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: Doctor Service
    description: Servicio para gestión de doctores
    version: 1.0.0
