spring:
  application:
    name: doctor-service
  cloud:
    compatibility-verifier:
      enabled: false # Opcional para evitar errores por versiones
  main:
    allow-bean-definition-overriding: true # Si usás Feign más adelante
  datasource:
    url: "jdbc:h2:mem:hospitaldb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
  data:
    elasticsearch:
      #uris: http://localhost:9200
      uris: "https://j78qu5rxgf:c3y0l8bm9z@hospital-cluster-5303791460.us-east-1.bonsaisearch.net:443"
      connection-timeout: 30s
      socket-timeout: 30s
      # Configuración SSL para Bonsai
      ssl:
        enabled: true
        verification-mode: none
      # Configuración de cluster
      cluster-name: hospital-cluster
      # Configuración de índices
      index:
        number-of-shards: 1
        number-of-replicas: 0
      # Configuración de búsqueda
      search:
        default-timeout: 30s
        max-timeout: 60s
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: true
    locations: classpath:db/migration

  jackson:
    default-property-inclusion: non-null
    serialization:
      write-dates-as-timestamps: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
