spring:
  application:
    name: eureka-server
  config:
    import: optional:configserver

server:
  port: 8761

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    # Uncomment the following line if you want to register with Eureka
    register-with-eureka: true
    # Uncomment the following line if you want to fetch the registry
    fetch-registry: false
  instance:
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}
  server:
    enable-self-preservation: false
  healthcheck:
    enabled: true
    instance-info-replication-interval-seconds: 5
  
management:
  endpoints:
    web:
      exposure:
        include: health, info, eureka, metrics
  endpoint:
    eureka:
      enabled: true
  info:
    env:
      enabled: true
      
info:
  app:
    name: Eureka Server
    description: Service Registry for Microservices
    version: 1.0.0
    