spring:
  application:
    name: eureka-server
  config:
    import: optional:configserver

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
  instance:
    prefer-ip-address: true
    hostname: localhost
  healthcheck:
    enabled: true
  instance-info-replication-interval-seconds: 10
  
management:
  endpoints:
    web:
      exposure:
        include: health, info, eureka, metrics
  endpoint:
    eureka:
      enabled: true
  info:
    env:
      enabled: true
      
info:
  app:
    name: Eureka Server
    description: Service Registry for Microservices
    version: 1.0.0
    